const data = {
    galeryTitle:"Your title",
    galeryItems: 
    [
        {
            name:"Catty",
            image:"./images/client-1.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-2.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-3.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-4.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-5.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-6.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-7.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-8.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-9.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
        {
            name:"Catty",
            image:"./images/client-10.jpg",
            link:"https://www.instagram.com/alejandrovaqueral",
            iconUrl:"./icons/instagram-icon.png",
        },
    ],

};

